/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PeminjamanController;
import Model.PeminjamanModel;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Nabil Ma'ru
 */
public class MenuLihatRuangan extends javax.swing.JFrame {
    private PeminjamanController controller;
    /**
     * Creates new form MenuUtama
     */
    public MenuLihatRuangan() throws SQLException {
        initComponents();
        controller = new PeminjamanController();
        loadTableData();
    }

    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0); // Hapus data sebelumnya tanpa menghapus kolom

        try {
            List<PeminjamanModel> peminjamanList = controller.getAllPeminjaman();

            // Cek jika data kosong
            if (peminjamanList == null || peminjamanList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tidak ada data peminjaman yang tersedia.");
                return;
            }

            // Loop untuk menambahkan data ke dalam tabel
            for (PeminjamanModel peminjaman : peminjamanList) {
                Object[] rowData = {
                    peminjaman.getId(),
                    peminjaman.getIdStaf(),
                    peminjaman.getNim(),
                    peminjaman.getKelas(),
                    peminjaman.getProdi(),
                    peminjaman.getTanggal(),
                    peminjaman.getWaktu(),
                    peminjaman.getStatus()
                };
                model.addRow(rowData); // Tambahkan data ke tabel
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memuat data peminjaman.");
            ex.printStackTrace(); // Tambahkan logging untuk memeriksa kesalahan
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CariButton = new javax.swing.JButton();
        CariField = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        UrutkanField = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"C404", "Sistem Informasi", "Senin, 26 Juni 2024", "07.30 - 09.00", "Unavailable", null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Kelas", "ID Staf", "NIM PJ", "Kelas", "Prodi", "Tanggal", "Waktu", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFillsViewportHeight(true);
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 1030, 500));

        CariButton.setBackground(new java.awt.Color(102, 102, 255));
        CariButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        CariButton.setText("Cari");
        CariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CariButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 80, 40));

        CariField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        CariField.setForeground(new java.awt.Color(0, 0, 0));
        CariField.setText("Masukkan Program Studi Anda");
        CariField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariFieldActionPerformed(evt);
            }
        });
        getContentPane().add(CariField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 220, 40));

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 150, 40));

        UrutkanField.setBackground(new java.awt.Color(39, 45, 90));
        UrutkanField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        UrutkanField.setForeground(new java.awt.Color(255, 255, 255));
        UrutkanField.setText("Urutkan");
        UrutkanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrutkanFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UrutkanField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, 40));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 45, 90));
        jLabel3.setText("ClassThink");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 50));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fakultas Teknik Universitas Mulawarman");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sistem Aplikasi Peminjaman Ruangan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled design (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariButtonActionPerformed
        // TODO add your handling code here:
    // Ambil teks dari CariField (textfield pencarian)
    String prodi = CariField.getText().trim();  // Pastikan mendapatkan input teks dari CariField

    if (!prodi.isEmpty()) {
        // Panggil fungsi untuk mencari berdasarkan prodi dan memperbarui tabel
        controller.searchAndDisplayByProdi(jTable1, prodi); // Memperbarui jTable1 dengan hasil pencarian
    } else {
        JOptionPane.showMessageDialog(this, "Silakan masukkan Prodi untuk pencarian.");
    }
    }//GEN-LAST:event_CariButtonActionPerformed

    private void UrutkanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrutkanFieldActionPerformed
        // TODO add your handling code here:
        controller.sortPeminjaman(jTable1);
    }//GEN-LAST:event_UrutkanFieldActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MenuUser mu = new MenuUser();
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void CariFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariFieldActionPerformed
        // TODO add your handling code here:
    // Ambil teks dari CariField
    String prodi = CariField.getText().trim();  // Pastikan mendapatkan input teks dari CariField

    if (!prodi.isEmpty()) {
        // Panggil fungsi untuk mencari berdasarkan prodi dan memperbarui tabel
        controller.searchAndDisplayByProdi(jTable1, prodi); // Memperbarui jTable1 dengan hasil pencarian
    } else {
        JOptionPane.showMessageDialog(this, "Silakan masukkan Prodi untuk pencarian.");
    }
    }//GEN-LAST:event_CariFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLihatRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLihatRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLihatRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLihatRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuLihatRuangan().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MenuLihatRuangan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CariButton;
    private javax.swing.JTextField CariField;
    private javax.swing.JButton UrutkanField;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
