/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PeminjamanController;
import Model.PeminjamanModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Nabil Ma'ru
 */
public class StaffEdit extends javax.swing.JFrame {
    // Metode untuk mengatur data di form StaffEdit
    public void setData(String idPeminjaman, String namaKelas, String prodi, String hariTanggal, String waktu, String status) {
        // Misal Anda memiliki JTextField dan JComboBox untuk setiap data
        IDkelasField.setText(idPeminjaman);  // Mengisi JTextField untuk ID Peminjaman
        KelasComboBox.setSelectedItem(namaKelas);        // Mengisi JTextField untuk Nama Kelas

        // Atur ComboBox Prodi sesuai data yang dipilih
        ProdiComboBox.setSelectedItem(prodi);

        // Mengisi JTextField untuk tanggal
        TanggalField.setText(hariTanggal);

        // Atur ComboBox Waktu sesuai data yang dipilih
        WaktuComboBox.setSelectedItem(waktu);

        // Atur ComboBox Status sesuai data yang dipilih
        StatusComboBox.setSelectedItem(status);
    }
    public StaffEdit() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TanggalField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        PerbaruiButton = new javax.swing.JButton();
        IDkelasField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        WaktuComboBox = new javax.swing.JComboBox<>();
        KelasComboBox = new javax.swing.JComboBox<>();
        ProdiComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 64)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, 70));

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Selamat Datang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, 70));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel6.setText("Prodi");

        TanggalField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        TanggalField.setForeground(new java.awt.Color(0, 0, 0));
        TanggalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel7.setText("Hari & Tanggal");

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel8.setText("Jam");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel2.setText("Kelas");

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        PerbaruiButton.setBackground(new java.awt.Color(39, 45, 90));
        PerbaruiButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        PerbaruiButton.setForeground(new java.awt.Color(255, 255, 255));
        PerbaruiButton.setText("Perbarui");
        PerbaruiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerbaruiButtonActionPerformed(evt);
            }
        });

        IDkelasField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        IDkelasField.setForeground(new java.awt.Color(0, 0, 0));
        IDkelasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDkelasFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel5.setText("ID Kelas");

        StatusComboBox.setForeground(new java.awt.Color(0, 0, 0));
        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Menunggu", "Dipinjam" }));
        StatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel9.setText("Status");

        WaktuComboBox.setForeground(new java.awt.Color(0, 0, 0));
        WaktuComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "7:30 - 9:00", "9:10 - 10:40", "10:50 - 12:20", "13:00 - 14:30", "14:40 - 16:10" }));
        WaktuComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaktuComboBoxActionPerformed(evt);
            }
        });

        KelasComboBox.setForeground(new java.awt.Color(0, 0, 0));
        KelasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A101", "A102", "A103", "A104", "B201", "B202", "B203", "C302", "C303", "D401", "D402", "D404" }));
        KelasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasComboBoxActionPerformed(evt);
            }
        });

        ProdiComboBox.setForeground(new java.awt.Color(0, 0, 0));
        ProdiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Teknik Sipil", "Teknik Industri", "Teknik Lingkungan", "Teknik Informatika", "Sistem Informasi", "Teknik Pertambangan", "Teknik Elektro", "Teknik Arsitektur", "Teknik Geologi", "Teknik Kimia" }));
        ProdiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdiComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PerbaruiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StatusComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TanggalField)
                            .addComponent(IDkelasField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(KelasComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WaktuComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProdiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDkelasField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(KelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ProdiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(WaktuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerbaruiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 600, 430));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled design (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TanggalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalFieldActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            MenuStaff ma = new MenuStaff();
            ma.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(StaffEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void PerbaruiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerbaruiButtonActionPerformed
        // TODO add your handling code here:
    // Ambil nilai dari form
    String idPeminjaman = IDkelasField.getText();
    String status = (String) StatusComboBox.getSelectedItem();
    String kelas = (String) KelasComboBox.getSelectedItem();
    String waktu = (String) WaktuComboBox.getSelectedItem();
    String prodi = (String) ProdiComboBox.getSelectedItem();
    String tanggal = TanggalField.getText();
    String idStaf = "S001";
    String nim = "";
    // Validasi data input
    if (idPeminjaman.isEmpty() || status == null || kelas == null) {
        JOptionPane.showMessageDialog(null, "Data tidak lengkap! Pastikan ID kelas dan status sudah dipilih.");
        return;
    }

    // Set prodi, nim, dan tanggal menjadi null jika menggunakan '-'
    if (status.equals("Tersedia")) {
        prodi = "-";
        tanggal = "-";
    }

    // Membuat objek PeminjamanModel
    PeminjamanModel peminjaman = new PeminjamanModel(idPeminjaman, idStaf, nim, kelas, prodi, tanggal, waktu, status);

    // Menggunakan controller untuk mengedit data
    try {
        PeminjamanController controller = new PeminjamanController();
        boolean result = controller.editPeminjaman(peminjaman);

        if (result) {
            JOptionPane.showMessageDialog(null, "Data peminjaman berhasil diperbarui.");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal memperbarui data peminjaman.");
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menghubungkan ke database.");
    }
    }//GEN-LAST:event_PerbaruiButtonActionPerformed

    private void IDkelasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDkelasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDkelasFieldActionPerformed

    private void StatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusComboBoxActionPerformed

    private void KelasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelasComboBoxActionPerformed

    private void WaktuComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaktuComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaktuComboBoxActionPerformed

    private void ProdiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdiComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(StaffEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(StaffEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(StaffEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(StaffEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Menampilkan form kosong
            new StaffEdit().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDkelasField;
    private javax.swing.JComboBox<String> KelasComboBox;
    private javax.swing.JButton PerbaruiButton;
    private javax.swing.JComboBox<String> ProdiComboBox;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JTextField TanggalField;
    private javax.swing.JComboBox<String> WaktuComboBox;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
