/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PeminjamanController;
import Model.PeminjamanModel;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Nabil Ma'ru
 */
public class StaffTambah extends javax.swing.JFrame {

    /**
     * Creates new form PilihanAdmin
     */
    public StaffTambah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NIMfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TanggalField = new javax.swing.JTextField();
        TambahField = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ComboBoxStatus = new javax.swing.JComboBox<>();
        ComboBoxKelas = new javax.swing.JComboBox<>();
        ComboBoxWaktu = new javax.swing.JComboBox<>();
        ComboBoxKelas1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Selamat Datang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, 70));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 64)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, 70));

        NIMfield.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        NIMfield.setForeground(new java.awt.Color(0, 0, 0));
        NIMfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIMfieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel2.setText("Kelas");

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel6.setText("Prodi");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel7.setText("Hari & Tanggal");

        TanggalField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        TanggalField.setForeground(new java.awt.Color(0, 0, 0));
        TanggalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalFieldActionPerformed(evt);
            }
        });

        TambahField.setBackground(new java.awt.Color(39, 45, 90));
        TambahField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        TambahField.setForeground(new java.awt.Color(255, 255, 255));
        TambahField.setText("Tambahkan");
        TambahField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahFieldActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel8.setText("Jam");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel5.setText("NIM");

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel10.setText("Status");

        ComboBoxStatus.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Menunggu", "Dipinjam" }));
        ComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxStatusActionPerformed(evt);
            }
        });

        ComboBoxKelas.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A101", "A102", "A103", "A104", "B201", "B202", "B203", "C302", "C303", "D401", "D402", "D404" }));
        ComboBoxKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKelasActionPerformed(evt);
            }
        });

        ComboBoxWaktu.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:30 - 9:00", "9:10 - 10:40", "10:50 - 12:20", "13:00 - 14:30", "14:40 - 16:10" }));
        ComboBoxWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxWaktuActionPerformed(evt);
            }
        });

        ComboBoxKelas1.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxKelas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Teknik Sipil", "Teknik Industri", "Teknik Lingkungan", "Teknik Informatika", "Sistem Informasi", "Teknik Pertambangan", "Teknik Elektro", "Teknik Arsitektur", "Teknik Geologi", "Teknik Kimia" }));
        ComboBoxKelas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKelas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TambahField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TanggalField, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                .addComponent(NIMfield)
                                .addComponent(ComboBoxKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboBoxStatus, 0, 345, Short.MAX_VALUE)
                                .addComponent(ComboBoxWaktu, 0, 345, Short.MAX_VALUE))
                            .addComponent(ComboBoxKelas1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIMfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBoxKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxKelas1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 620, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled design (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            MenuStaff ma = new MenuStaff();
            ma.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(StaffTambah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TambahFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahFieldActionPerformed
        // TODO add your handling code here:
    try {
        // Mengambil input dari form
        String id = "";
        String idStaf = "";  // Default value atau bisa diisi sesuai kebutuhan
        String tanggal = TanggalField.getText();
        String nim = NIMfield.getText();
        String kelas = (String) ComboBoxKelas.getSelectedItem();
        String prodi = (String) ComboBoxKelas1.getSelectedItem();
        String waktu = (String) ComboBoxWaktu.getSelectedItem();
        String status = (String) ComboBoxStatus.getSelectedItem();

        // Validasi field tidak boleh kosong
        if (tanggal.isEmpty() || nim.isEmpty() || kelas == null || prodi == null || waktu == null || status == null) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Hentikan proses jika ada field yang kosong
        }

        // Validasi format tanggal
        if (!isValidDateFormat(tanggal)) {
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid! Gunakan format yyyy/mm/dd.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Hentikan proses jika format tanggal tidak valid
        }

        // Membuat objek PeminjamanModel untuk menyimpan data
        PeminjamanModel peminjaman = new PeminjamanModel(id,idStaf, nim, kelas, prodi, tanggal, waktu, status);

        // Memanggil method insertPeminjaman dari controller
        PeminjamanController controller = new PeminjamanController();
        boolean berhasil = controller.insertPeminjaman(peminjaman);

        if (berhasil) {
            JOptionPane.showMessageDialog(this, "Data peminjaman berhasil ditambahkan!");
        } else {
            
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data peminjaman.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    // Metode validasi format tanggal
    private boolean isValidDateFormat(String date) {
        try {
            // Pastikan format tanggal menggunakan yyyy/MM/dd
            new SimpleDateFormat("yyyy/mm/dd").parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
    

    }//GEN-LAST:event_TambahFieldActionPerformed

    private void TanggalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalFieldActionPerformed

    private void NIMfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIMfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIMfieldActionPerformed

    private void ComboBoxKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxKelasActionPerformed

    private void ComboBoxWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxWaktuActionPerformed

    private void ComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxStatusActionPerformed

    private void ComboBoxKelas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKelas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxKelas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffTambah().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxKelas;
    private javax.swing.JComboBox<String> ComboBoxKelas1;
    private javax.swing.JComboBox<String> ComboBoxStatus;
    private javax.swing.JComboBox<String> ComboBoxWaktu;
    private javax.swing.JTextField NIMfield;
    private javax.swing.JButton TambahField;
    private javax.swing.JTextField TanggalField;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
